security:
    # Proveedores de usuarios que pueden usar los firewalls:
    providers:
        app_user_provider:
            entity:
                class: App\Entity\Usuario     # La entidad
                property: email               # Atributo de la clase que es el nombre de usuario

    # Hasheo de las claves de los usuarios
    password_hashers:
        App\Entity\Usuario:
            algorithm: auto

    # Firewalls (hay 2, si te fijas)
    firewalls:
        dev:                                  # ===== Firewall de desarrollo ===== no lo toques
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:                                 # ===== Firewall principal =====
            lazy: true                        # Todas las páginas se pueden ver estando autorizado (o no)
            provider: app_user_provider       # Los usuarios salen del proveedor declarado arriba

            form_login:
                login_path: app_login         # Ruta al controlador de login
                check_path: app_login         # Ruta a la que se envían el POST del formulario de login
                default_target_path: portal_principal   # Después de login correcto

            logout:
                path: /logout                 # Ruta para hacer el logout
                target: app_login             # Después de logout, vuelve al login

    access_control:                           # Qué páginas se protegen y cuáles no
        # Páginas públicas
        - { path: ^/login,    roles: PUBLIC_ACCESS }
        - { path: ^/registro, roles: PUBLIC_ACCESS }

        # Preparado: cuando tengas /portal, solo usuarios logueados
        - { path: ^/portal,   roles: ROLE_USER }

        # Preparado: cuando tengas /admin, solo admins
        - { path: ^/admin,    roles: ROLE_ADMIN }
